repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=20480"]
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: npx biome check .
        language: system
        types: [javascript, jsx, tsx, json]
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
