name: Deploy to DO

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Deploy
      env:
        HOST: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        echo "Deploying to $HOST as $USERNAME"
        ssh -o StrictHostKeyChecking=no -i - ${USERNAME}@${HOST} << EOF
          cd /var/www/kabilan108.com
          git pull origin main
          git submodule update --recursive --remote
          docker compose down
          docker compose up -d --build
        EOF
